//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WashZa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Laundry
    {
        public string Id { get; set; }
        public Nullable<int> Active { get; set; }
    }
}
